#!/usr/bin/env python3
"""
Exploratory Option C pair-selector split encoder for the (3,4) Step 0 check.

The bundled package is generated by the repository generator. This module
generates only the split liberalism representation:

    minlib -> {selected_decisive_left, selected_decisive_right}

Both split levers share one voter-pair selector bank, so they refer to the same
selected witness pair. They use separate role-specific decisive-selector banks:

    left:  decisive selectors for voters that occur on the left of an ordered
           canonical voter pair;
    right: decisive selectors for voters that occur on the right.

For n=3 and canonical pairs (0,1), (0,2), (1,2), voter 1 occurs in both roles.
It therefore has distinct left and right decisive-selector series. This is the
representation-level machinery whose effect on clause-multiset equivalence is
measured by Step 0.

This module is intentionally isolated under scripts/exploration/candidate_b/.
It does not modify encoding/schema.py or the top-level generator registry.
It is the exploratory Option C voter-dimension boundary track, not the Option D
positive track. Its output must not be used to claim ≡CM-protected repair
non-canonicity, and it does not authorize repair enumeration.
"""

from __future__ import annotations

import hashlib
import itertools
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from encoding.axioms import AXIOM_REGISTRY  # noqa: E402
from encoding.schema import FiniteSchema  # noqa: E402

ENCODING_LABEL = "option_c_pair_selector_split_v0"
TARGET_CASE = (3, 4)

SHARED_LEVERS = {"asymm", "un", "no_cycle3", "no_cycle4"}
SPLIT_LEVERS = {"selected_decisive_left", "selected_decisive_right"}
KNOWN_LEVERS = SHARED_LEVERS | SPLIT_LEVERS
CANONICAL_ORDER = [
    "asymm",
    "un",
    "selected_decisive_left",
    "selected_decisive_right",
    "no_cycle3",
    "no_cycle4",
]


class _ClauseWriter:
    def __init__(self, path: Path) -> None:
        self.path = path
        self._file = path.open("w", encoding="ascii")
        self._count = 0

    def append(self, clause: list[int]) -> None:
        self._file.write(" ".join(str(lit) for lit in clause))
        self._file.write(" 0\n")
        self._count += 1

    def __len__(self) -> int:
        return self._count

    def close(self) -> None:
        self._file.close()


class _OptionCLayout:
    """Pair selectors plus separate left/right decisive-selector banks."""

    def __init__(self, schema: FiniteSchema) -> None:
        self.schema = schema
        self.voter_pairs = list(itertools.combinations(schema.voters, 2))
        self.voter_pair_idx = {
            pair: idx for idx, pair in enumerate(self.voter_pairs)
        }
        self.left_voters = sorted({i for i, _ in self.voter_pairs})
        self.right_voters = sorted({j for _, j in self.voter_pairs})
        self.left_voter_idx = {
            voter: idx for idx, voter in enumerate(self.left_voters)
        }
        self.right_voter_idx = {
            voter: idx for idx, voter in enumerate(self.right_voters)
        }

        self.pair_start = schema.n_p_vars + 1
        self.pair_end = self.pair_start + len(self.voter_pairs) - 1
        self.left_start = self.pair_end + 1
        self.left_end = (
            self.left_start + len(self.left_voters) * schema.n_pairs - 1
        )
        self.right_start = self.left_end + 1
        self.right_end = (
            self.right_start + len(self.right_voters) * schema.n_pairs - 1
        )
        self.nvars = self.right_end

    def pair(self, i: int, j: int) -> int:
        pair = (i, j) if i < j else (j, i)
        return self.pair_start + self.voter_pair_idx[pair]

    def left(self, voter: int, a: int, b: int) -> int:
        return (
            self.left_start
            + self.left_voter_idx[voter] * self.schema.n_pairs
            + self.schema.pair_idx[(a, b)]
        )

    def right(self, voter: int, a: int, b: int) -> int:
        return (
            self.right_start
            + self.right_voter_idx[voter] * self.schema.n_pairs
            + self.schema.pair_idx[(a, b)]
        )


def _social_lit(
    schema: FiniteSchema, p: int, voter: int, a: int, b: int
) -> int:
    return (
        schema.var_p(p, a, b)
        if schema.prefers(p, voter, a, b)
        else schema.var_p(p, b, a)
    )


def _emit_pair_selection(
    layout: _OptionCLayout, out: _ClauseWriter
) -> None:
    out.append([layout.pair(i, j) for i, j in layout.voter_pairs])


def _emit_left(
    schema: FiniteSchema, layout: _OptionCLayout, out: _ClauseWriter
) -> None:
    for i, j in layout.voter_pairs:
        out.append(
            [-layout.pair(i, j)]
            + [layout.left(i, a, b) for a, b in schema.pairs]
        )
    for voter in layout.left_voters:
        for a, b in schema.pairs:
            decisive = layout.left(voter, a, b)
            for p in range(schema.n_profiles):
                out.append(
                    [-decisive, _social_lit(schema, p, voter, a, b)]
                )


def _emit_right(
    schema: FiniteSchema, layout: _OptionCLayout, out: _ClauseWriter
) -> None:
    for i, j in layout.voter_pairs:
        out.append(
            [-layout.pair(i, j)]
            + [layout.right(j, a, b) for a, b in schema.pairs]
        )
    for voter in layout.right_voters:
        for a, b in schema.pairs:
            decisive = layout.right(voter, a, b)
            for p in range(schema.n_profiles):
                out.append(
                    [-decisive, _social_lit(schema, p, voter, a, b)]
                )


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def generate_split_package(
    *,
    n: int,
    m: int,
    axiom_names: list[str],
    out_path: Path,
    manifest_path: Path,
) -> dict[str, object]:
    if (n, m) != TARGET_CASE:
        raise ValueError(
            f"Option C Step 0 is restricted to target {TARGET_CASE}; got {(n, m)}"
        )
    unknown = [name for name in axiom_names if name not in KNOWN_LEVERS]
    if unknown:
        raise ValueError(f"unknown Option C lever(s): {unknown}")
    if len(set(axiom_names)) != len(axiom_names):
        raise ValueError("duplicate levers are not allowed")
    if not SPLIT_LEVERS.issubset(axiom_names):
        raise ValueError(
            "Option C Step 0 requires both selected_decisive_left and "
            "selected_decisive_right"
        )

    schema = FiniteSchema(n=n, m=m, minlib_mode="disabled")
    layout = _OptionCLayout(schema)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    body_path = out_path.with_suffix(out_path.suffix + ".body.tmp")
    writer = _ClauseWriter(body_path)
    per_lever: dict[str, int] = {}
    component_counts: dict[str, int] = {}
    try:
        for lever in CANONICAL_ORDER:
            if lever not in axiom_names:
                continue
            if lever == "selected_decisive_left":
                before_shared = len(writer)
                _emit_pair_selection(layout, writer)
                component_counts["shared_pair_selection"] = (
                    len(writer) - before_shared
                )
                before = len(writer)
                _emit_left(schema, layout, writer)
                per_lever[lever] = len(writer) - before
                component_counts["left_pair_support"] = len(layout.voter_pairs)
                component_counts["left_decisive_implications"] = (
                    len(layout.left_voters)
                    * schema.n_pairs
                    * schema.n_profiles
                )
            elif lever == "selected_decisive_right":
                before = len(writer)
                _emit_right(schema, layout, writer)
                per_lever[lever] = len(writer) - before
                component_counts["right_pair_support"] = len(layout.voter_pairs)
                component_counts["right_decisive_implications"] = (
                    len(layout.right_voters)
                    * schema.n_pairs
                    * schema.n_profiles
                )
            else:
                before = len(writer)
                AXIOM_REGISTRY[lever].encode(schema, writer)
                per_lever[lever] = len(writer) - before
    finally:
        writer.close()

    nclauses = len(writer)
    with out_path.open("w", encoding="ascii") as out:
        out.write(f"p cnf {layout.nvars} {nclauses}\n")
        with body_path.open("r", encoding="ascii") as body:
            for chunk in iter(lambda: body.read(1024 * 1024), ""):
                out.write(chunk)
    body_path.unlink(missing_ok=True)

    manifest = {
        "encoding": ENCODING_LABEL,
        "n": n,
        "m": m,
        "axioms": list(axiom_names),
        "nvars": layout.nvars,
        "nclauses": nclauses,
        "n_p_vars": schema.n_p_vars,
        "per_lever_clause_counts": per_lever,
        "component_clause_counts": component_counts,
        "cnf_sha256": _sha256(out_path),
        "uses_pair_selectors": True,
        "pair_selector_order": [list(pair) for pair in layout.voter_pairs],
        "pair_selector_var_range": [layout.pair_start, layout.pair_end],
        "left_decisive_voters": layout.left_voters,
        "left_decisive_var_range": [layout.left_start, layout.left_end],
        "right_decisive_voters": layout.right_voters,
        "right_decisive_var_range": [layout.right_start, layout.right_end],
        "shared_infrastructure": {
            "pair_selection_clause_count": component_counts[
                "shared_pair_selection"
            ],
            "ownership": (
                "emitted once for the active split package; both split levers "
                "refer to the same selected witness pair"
            ),
        },
        "note": (
            "Exploratory Option C split with a shared pair-selector bank and "
            "separate left/right decisive-selector banks. No schema or registry "
            "changes."
        ),
    }
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest
