#!/usr/bin/env python3
"""
M2.1 Option C Step 0 feasibility check for the (3,4) voter boundary.

The bundled package is generated by the repository's real parametric generator.
The split package uses the exploratory Option C encoder with one shared
voter-pair selector bank and separate left/right decisive-selector banks.

This script classifies only Step 0:
  * equiv_cm_persists
  * sat_equiv_only
  * status_diverges
  * inconclusive

It never enumerates repairs. Outputs go to /tmp by default.

This is the exploratory Option C voter-dimension boundary track, not Option D.
In particular, a sat_equiv_only result must not be used to claim an
≡CM-protected repair non-canonicity result, and does not authorize repair
enumeration.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import time
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
SCRIPTS_DIR = HERE.parents[1]
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import option_c_encoder  # noqa: E402
from gen_dimacs import run_generation  # noqa: E402
from step0_equiv_check import (  # noqa: E402
    CLASS_EQUIV_CM,
    CLASS_INCONCLUSIVE,
    CLASS_SAT_EQUIV,
    CLASS_STATUS_DIVERGES,
    SCOPE_STATEMENT,
    _package_id,
    _parse_clauses,
    find_renaming,
)

TARGET_CASE = (3, 4)
BUNDLED_PACKAGE = ["asymm", "un", "minlib", "no_cycle3", "no_cycle4"]
SPLIT_PACKAGE = [
    "asymm",
    "un",
    "selected_decisive_left",
    "selected_decisive_right",
    "no_cycle3",
    "no_cycle4",
]
TRANSPORT_MAP = {
    "minlib": ["selected_decisive_left", "selected_decisive_right"],
    "asymm": ["asymm"],
    "un": ["un"],
    "no_cycle3": ["no_cycle3"],
    "no_cycle4": ["no_cycle4"],
}


def _read_header(path: Path) -> tuple[int, int]:
    with path.open("r", encoding="ascii") as source:
        for raw in source:
            line = raw.strip()
            if not line or line.startswith("c"):
                continue
            fields = line.split()
            if len(fields) != 4 or fields[:2] != ["p", "cnf"]:
                raise ValueError(f"invalid DIMACS header in {path}: {line!r}")
            return int(fields[2]), int(fields[3])
    raise ValueError(f"missing DIMACS header in {path}")


def _clause_length_histogram(path: Path) -> dict[str, int]:
    counts: Counter[int] = Counter()
    with path.open("r", encoding="ascii") as source:
        for raw in source:
            line = raw.strip()
            if not line or line.startswith("c") or line.startswith("p "):
                continue
            fields = line.split()
            if fields[-1] != "0":
                raise ValueError(f"malformed DIMACS clause in {path}: {line!r}")
            counts[len(fields) - 1] += 1
    return {str(length): count for length, count in sorted(counts.items())}


def _distinct_used_variable_count(path: Path) -> int:
    variables: set[int] = set()
    with path.open("r", encoding="ascii") as source:
        for raw in source:
            line = raw.strip()
            if not line or line.startswith("c") or line.startswith("p "):
                continue
            fields = line.split()
            if fields[-1] != "0":
                raise ValueError(f"malformed DIMACS clause in {path}: {line!r}")
            variables.update(abs(int(field)) for field in fields[:-1])
    return len(variables)


def _solve(
    path: Path, *, solver: str, timeout_sec: float
) -> dict[str, Any]:
    solver_path = shutil.which(solver)
    if solver_path is None:
        return {
            "status": None,
            "detail": f"solver {solver!r} not found",
            "duration_sec": 0.0,
        }
    started = time.perf_counter()
    try:
        proc = subprocess.run(
            [solver_path, str(path)],
            capture_output=True,
            text=True,
            check=False,
            timeout=timeout_sec,
        )
    except subprocess.TimeoutExpired:
        return {
            "status": None,
            "detail": f"timeout after {timeout_sec:.3f}s",
            "duration_sec": time.perf_counter() - started,
        }
    duration = time.perf_counter() - started
    if proc.returncode == 10:
        status = "SAT"
    elif proc.returncode == 20:
        status = "UNSAT"
    else:
        text = f"{proc.stdout}\n{proc.stderr}".upper()
        if "UNSATISFIABLE" in text:
            status = "UNSAT"
        elif "SATISFIABLE" in text:
            status = "SAT"
        else:
            status = None
    return {
        "status": status,
        "detail": f"rc={proc.returncode}",
        "duration_sec": duration,
    }


def run(
    *,
    outdir: Path,
    solver: str,
    solve_timeout_sec: float,
) -> dict[str, Any]:
    n, m = TARGET_CASE
    case_dir = outdir / "n3_m4"
    case_dir.mkdir(parents=True, exist_ok=True)
    bundled_cnf = case_dir / "bundled.cnf"
    bundled_manifest_path = case_dir / "bundled.manifest.json"
    split_cnf = case_dir / "split.cnf"
    split_manifest_path = case_dir / "split.manifest.json"

    report: dict[str, Any] = {
        "case": {"n": n, "m": m},
        "track": "option_c_voter_boundary",
        "bundled_package": _package_id(BUNDLED_PACKAGE),
        "split_package": _package_id(SPLIT_PACKAGE),
        "transport_map": TRANSPORT_MAP,
        "transport_map_note": (
            "π is a lever correspondence / repair-transport map, not a "
            "semantic equivalence claim."
        ),
        "classification": CLASS_INCONCLUSIVE,
        "local_rationality_scope": SCOPE_STATEMENT,
        "repair_enumeration": "not run; not authorized by Step 0",
        "repair_enumeration_authorized": False,
        "claim_authorization": (
            "Step 0 boundary classification only; no ≡CM-protected repair "
            "non-canonicity claim is authorized."
        ),
    }

    try:
        bundled_manifest = run_generation(
            n=n,
            m=m,
            axiom_names=BUNDLED_PACKAGE,
            out_path=bundled_cnf,
            manifest_path=bundled_manifest_path,
        )
        split_manifest = option_c_encoder.generate_split_package(
            n=n,
            m=m,
            axiom_names=SPLIT_PACKAGE,
            out_path=split_cnf,
            manifest_path=split_manifest_path,
        )
    except Exception as exc:  # noqa: BLE001 - exploratory report records failure
        report["explanation"] = (
            f"generation failed: {type(exc).__name__}: {exc}"
        )
        return report

    bundled_nvars, bundled_nclauses = _read_header(bundled_cnf)
    split_nvars, split_nclauses = _read_header(split_cnf)
    bundled_hist = _clause_length_histogram(bundled_cnf)
    split_hist = _clause_length_histogram(split_cnf)
    bundled_used_variables = _distinct_used_variable_count(bundled_cnf)
    split_used_variables = _distinct_used_variable_count(split_cnf)

    report["bundled"] = {
        "encoding": bundled_manifest["encoding"],
        "minlib_mode": bundled_manifest["minlib"]["mode"],
        "nvars": bundled_nvars,
        "distinct_used_variables": bundled_used_variables,
        "nclauses": bundled_nclauses,
        "category_counts": bundled_manifest["category_counts"],
        "minlib_structure": bundled_manifest["minlib"],
        "clause_length_histogram": bundled_hist,
    }
    report["split"] = {
        "encoding": split_manifest["encoding"],
        "nvars": split_nvars,
        "distinct_used_variables": split_used_variables,
        "nclauses": split_nclauses,
        "per_lever_clause_counts": split_manifest[
            "per_lever_clause_counts"
        ],
        "component_clause_counts": split_manifest[
            "component_clause_counts"
        ],
        "pair_selector_var_range": split_manifest[
            "pair_selector_var_range"
        ],
        "left_decisive_var_range": split_manifest[
            "left_decisive_var_range"
        ],
        "right_decisive_var_range": split_manifest[
            "right_decisive_var_range"
        ],
        "clause_length_histogram": split_hist,
    }
    report["bundled_variable_count"] = bundled_nvars
    report["split_variable_count"] = split_nvars
    report["bundled_clause_count"] = bundled_nclauses
    report["split_clause_count"] = split_nclauses

    necessary = {
        "distinct_used_variable_count_equal": (
            bundled_used_variables == split_used_variables
        ),
        "clause_count_equal": bundled_nclauses == split_nclauses,
        "clause_length_histogram_equal": bundled_hist == split_hist,
    }
    necessary["all_hold"] = all(necessary.values())
    if necessary["all_hold"]:
        rho_result = find_renaming(
            _parse_clauses(bundled_cnf),
            _parse_clauses(split_cnf),
        )
        equivalence = {
            "verified": bool(rho_result["verified"]),
            "method": rho_result["method"],
            "reason": rho_result["reason"],
        }
    else:
        failed = [
            key for key, value in necessary.items()
            if key != "all_hold" and not value
        ]
        equivalence = {
            "verified": False,
            "method": "necessary-condition refutation",
            "reason": (
                "no variable-renaming bijection can make the clause multisets "
                f"equal because these necessary conditions fail: {failed}"
            ),
        }
    report["clause_multiset_equivalence"] = equivalence
    report["clause_multiset_equivalent"] = bool(equivalence["verified"])
    report["necessary_conditions_for_rho"] = necessary
    report["structural_delta"] = {
        "extra_split_variables": split_nvars - bundled_nvars,
        "extra_split_clauses": split_nclauses - bundled_nclauses,
        "cause": (
            "the split representation has separate left/right decisive-selector "
            "series for voter 1, which can occupy either role across the three "
            "candidate witness pairs"
        ),
    }

    bundled_solve = _solve(
        bundled_cnf, solver=solver, timeout_sec=solve_timeout_sec
    )
    split_solve = _solve(
        split_cnf, solver=solver, timeout_sec=solve_timeout_sec
    )
    report["bundled_status"] = bundled_solve["status"]
    report["split_status"] = split_solve["status"]
    report["bundled_status_detail"] = bundled_solve
    report["split_status_detail"] = split_solve

    b_status = bundled_solve["status"]
    s_status = split_solve["status"]
    if b_status not in {"SAT", "UNSAT"} or s_status not in {"SAT", "UNSAT"}:
        report["classification"] = CLASS_INCONCLUSIVE
        report["explanation"] = (
            "SAT/UNSAT status was not established for both packages; no "
            "boundary classification beyond inconclusive is permitted."
        )
    elif b_status != s_status:
        report["classification"] = CLASS_STATUS_DIVERGES
        report["explanation"] = (
            f"bundled status {b_status} differs from split status {s_status}; "
            "record an encoding-transfer boundary and do not enumerate repairs."
        )
    elif equivalence["verified"]:
        report["classification"] = CLASS_EQUIV_CM
        report["explanation"] = (
            f"status agrees ({b_status}) and a verified renaming witnesses ≡CM."
        )
    else:
        report["classification"] = CLASS_SAT_EQUIV
        report["explanation"] = (
            f"status agrees ({b_status}/{s_status}), but ≡CM is refuted by "
            "cardinality invariants. The pair-selector split introduces a "
            "role-specific decisive-selector series, especially the separate "
            "left/right voter-1 selector structure, and implication clauses "
            "with no one-to-one bundled counterpart. This is the Option C "
            "voter-dimension representation boundary. It must not be used to "
            "claim ≡CM-protected repair non-canonicity, and repair enumeration "
            "remains unauthorized after sat_equiv_only."
        )
    return report


def _summary(payload: dict[str, Any]) -> str:
    case = payload["case"]
    bundled = payload.get("bundled", {})
    split = payload.get("split", {})
    equivalence = payload.get("clause_multiset_equivalence", {})
    return "\n".join(
        [
            "# M2.1 Option C Step 0 voter-boundary report",
            "",
            f"Generated: {payload['generated_at_utc']}",
            "",
            f"Case: `({case['n']},{case['m']})`",
            f"Classification: `{payload['classification']}`",
            f"Bundled status: `{payload.get('bundled_status')}`",
            f"Split status: `{payload.get('split_status')}`",
            f"Bundled vars/clauses: `{bundled.get('nvars')}/{bundled.get('nclauses')}`",
            f"Split vars/clauses: `{split.get('nvars')}/{split.get('nclauses')}`",
            f"≡CM verified: `{equivalence.get('verified', False)}`",
            "",
            payload.get("explanation", ""),
            "",
            f"Scope: {payload['local_rationality_scope']}",
            "",
            "Step 0 only. Repair enumeration was not run and remains unauthorized.",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--outdir",
        type=Path,
        default=Path("/tmp/candidate_b_step0_option_c"),
    )
    parser.add_argument("--solver", default="cadical")
    parser.add_argument("--solve-timeout-sec", type=float, default=300.0)
    args = parser.parse_args()

    report = run(
        outdir=args.outdir,
        solver=args.solver,
        solve_timeout_sec=args.solve_timeout_sec,
    )
    payload = {
        "experiment": "m2.1_step0_option_c_voter_boundary",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        **report,
    }
    args.outdir.mkdir(parents=True, exist_ok=True)
    report_path = args.outdir / "step0_option_c_comparison.json"
    summary_path = args.outdir / "step0_option_c_summary.md"
    report_path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    summary_path.write_text(_summary(payload), encoding="utf-8")
    print(f"Wrote {report_path}")
    print(f"Wrote {summary_path}")
    print(
        f"  (3,4): {payload['classification']} "
        f"({payload.get('bundled_status')}/{payload.get('split_status')})"
    )
    print("Step 0 only — repair enumeration was NOT run.")


if __name__ == "__main__":
    main()
